### ISSUE TITLE
cannot swap. balance not show

### ISSUE THREAD

**Issue by mellow8** [Armin-FalDiS/shadow-finance#9]
![image](https://github.com/Armin-FalDiS/shadow-finance/assets/39056899/6639ee59-1d29-400a-bbcf-feb0ecc5b983)

**Comment by Armin-FalDiS** [comment]
Are you using Leo Wallet or Puzzle?
Puzzle seems to be having problems with Balance right now.

**Comment by mellow8** [comment]
use Puzzle.

**Comment by Armin-FalDiS** [comment]
Puzzle seems to be having problems. I tried on other dApps an it doesn't work.
It's Puzzle's problem not ours. Leo wallet works perfectly fine though.
Not sure about Avail though.

**Comment by Armin-FalDiS** [comment]
@mellow8 
After the recent patches from the Puzzle team we have updated the dApp too and now I believe the problems should be gone.
